[project]
name = "life"
version = "0.1.0"
description = "ADHD executive function rescue system"
authors = [
    {name = "tyson",email = "tyson.chan@proton.me"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.0.0",
]

[project.scripts]
life = "life.cli:main"

[tool.poetry]
packages = [{include = "life", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
